/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class baidu_com_ndkdemo_NativeMethod */

#ifndef _Included_baidu_com_ndkdemo_NativeMethod
#define _Included_baidu_com_ndkdemo_NativeMethod
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     baidu_com_ndkdemo_NativeMethod
 * Method:    getNativeStr
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_baidu_com_ndkdemo_NativeMethod_getNativeStr
  (JNIEnv *, jobject);

/*
 * Class:     baidu_com_ndkdemo_NativeMethod
 * Method:    callJavaCode
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_baidu_com_ndkdemo_NativeMethod_callJavaCode
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
